#set document(
  title: "Some properties concerning derviations of affine domains",
  author: "Xiaosong Sun",
)

#set page(paper: "a4")
#set heading(numbering: "1.")
#set math.equation(numbering: "(1)")

#align(center)[
  #text(size: 2em, weight: "bold")[Some properties concerning derviations of affine domains]

  #text(size: 1.2em)[Xiaosong Sun]

  #datetime.today().display()
]

           \*

 /* \maketitle */

== Derivations theory and affine algebraic geometry
 Affine algebraic geometry mainly studies $bb(A)^(n)$. (Mathematics Subject Classification: 14R)

 relations:

  -  lnd and $bb(G)_(a)$ group actions on varieties
  -  kernel of lnd and Hilbert 14'th problem
  -  exponential of lnd and automorphism group
  -  images of derivations and Jacobian conjecture
  -  ML-inv and concellation problem for varieties

 A derivation $D $ of $B $ is locally nilpotent if for any $a in b $ there is a integer $n_(a)$ such that $D^(n_(a))(a)= 0 $. Then for $c h a r(k)= 0 $, lnd $D $, then $  exp D = sum_(n = 0)^(infinity)frac(D^(n), n !)  $ Let $X $ be an affine variety, then there are exponential automorphisms of $X $.

 Conjecture: $ op("Aut") bb(A)^(n)$ is generated by affine automorphism and exponential automorphism.

 Hilbert 14:

 a lnd $D $ of $k[x_(1),...,x_(n)]$ $  F r a c(ker D) sect k[x_(1),...,x_(n)]= ker D  $ Then there are conterexamples for hilbert 14 with $n = 5,6,7 $
== image of LND
 Jacobson conjecture: $ op("det") J F $ non-zero constant, then $F $ automorphism.

 Image conjecture (Zhao,2010) implies Jacobian conjecture.

 MWZ problem (Essen-Wright-Zhao, 2011): $D $ derivation of $k[x,y ]$, with $ op("div") D = 0 $, Is $ op("Im") D $ a MZ subspace.

*Theorem 1.* _ JC of dimension 2 $=> $ MWZ holds in the case $1 in op("Im") D $ _

*Definition 1.*  A subspace of $M $ of $S $ is MZ subspace if  $  f^(m)in M,forall n => forall g in B, g f^(m)in M, m gt.double 0  $

 lnd conjecture: Let $D $ be a lnd of $B = k[x_(1),...,x_(n)]$, any idea $I $ of $B $, then $D I $ is a MZ subspace. Open for $n gt.eq.slant 2 $.

 Crucial problem: Describe polynomials $f $ with $f^(m)in op("Im") D forall m gt.eq.slant 1 $

  -  polytopes of Laurent polynomial
  -  Integrals of polynomial functions
  -  local slices (local slice construction) ( Daigle algebraic explains )
  -  Grobner basis

== ML-invariant
 Cancellation problem: for affine variety $X,Y $, does $X times bb(A)^(1)tilde.equiv Y times bb(A)^(1)$ imply $X tilde.equiv Y $? Fail for surfaces.

 ML-invariant: $  M L(B)= sect_(D in L N D(B)) ker D  $

