#set document(
  title: "On the Du Bois property of secant varieties",
  author: "Lei Song",
)

#set page(paper: "a4")
#set heading(numbering: "1.")
#set math.equation(numbering: "(1)")

#align(center)[
  #text(size: 2em, weight: "bold")[On the Du Bois property of secant varieties]

  #text(size: 1.2em)[Lei Song]
]


== Introduction to D.B
 $X $ smooth projective variety over $CC $, and $ dim X = n $ complex: $  0 -> cal(O)_(X) limits(arrow.r.long)^(d = partial) Omega^(1)-> ... -> O m e g a^(n)-> 0  $ there is a filtration of the cotangent sheaf: $  F^(0): 0 -> cal(O)_(X) limits(arrow.r.long)^(d = partial) Omega^(1)-> ... -> O m e g a^(n)-> 0  $ $  F^(1): 0 -> Omega^(1)-> ... -> Omega^(n)-> 0  $

 let $ G r^(p)_(F)#underline[Omega]_(X)^(dot)= Omega_(X)^(p)$

$ E_(1)^(p,q)= bb(H)^(q)(X,#underline[Omega]_(X)^(p)) => H^(p + q)(X,CC) $

*Definition 1.*  If $ cal(O)_(X)-> #underline[Omega]_(X^(0)) $ is quasi-isomorphism, then $ X $ is Du Bois.

*Proposition 1.* _property of Du Bois

  +  klt $=> $ rational singularity $=> $ Du Bois

 klt $=> $ log canonical $=> $ Du Bois
  +  A fibration $ cal(X) -> B $ such that $ cal(X)_(b) $ is D.B for all $b $. If $ cal(X)_(B_(0)) $ has $ S_(k) $ condition, then so is any $ cal(X)_(b) $
  + $ R^(q)f_(*)cal(O)_(X) $ is locally free and compatible with case change.
 _

 *Higher Du Bois*
*Definition 2.* Shen-Veriketesh-Vo Fix $ p in NN $, $X $ is $p $-Du bois if $X $ is semi-normal, and

  + $ h^(0)(#underline[Omega]_(X)^(k))-> #underline[Omega]_(X)^(k) $ is quasi-isomorphism for $ 0 <= k <= p $ (pre-$ p $-D.B.)
  + $ C o d i m(X_(s i n g),X)>= 2 p + 1 $
  + $ h^(0)(#underline[Omega]_(X)^(k))limits(arrow.r.long)^(tilde) #underline[Omega]_(X)^([k ]) $

*Definition 3.*  $X $ is $p $-rational singularity if $X $ is normal and

  + $ C o d i m(X_(s i n g),X)> 2 p + 1 $
  +  For log resolution $ f : hat(X) -> X $, and exceptional divisor $E $, there is $ R^(i)f_(*)(Omega_(X)^(K)(log E))= 0 $ for $ forall i >= -, 0 <= k <= p $ (pre-$ p $-rational)

_Remark 1._ some results

  +  And $ p $-rational $ => $ $ p $=Du bois.
  +  In lc I $ p - D B =>(p - q) $-rational
  +  In Non lc I $ p - D B(p - q) $-rational

== Singularity of secant varieties
 Secant varieties $ Sigma_(k) $ of a variety $X arrow.r.hook bb(P)^(N)$ is defined as union of $k $-planes generated by points in $X $.

_Remark 2._  For $ X arrow.r.hook bb(P)^(N) $ by $ | L | $, if $L $ hhas insufficient positive, then degenerate: $ dim Sigma_(k) < $ expected. (expecte $ dim Sigma^(k)= k +(k + 1)n $)

 Example: consider $ bb(P)^(2)arrow.r.hook bb(P)^(5) $, then $ Sigma $ is a hypersurface.

_Remark 3._  Assume that

*Theorem 1.* _Wlley,Vermeire $ Sigma $ is normal. _

*Theorem 2.* _Chou-S

  - $ Sigma $ has worst D.B.
  - $ Sigma $ is C.M. if and only if $ h^(1)(X,cal(O))= ...= h^(n - 1)(X,cal(O))= 0 . $
  - $ omega^(G R)_(X)tilde.equiv omega $ if and only if $ h^(n)(X,cal(O))= 0 $
 _

== Geometry of secant varieties
 $ X^([2 ]) $ Hibert scheme of $ 2 $-points on $X $. Then $  xymatrix Phi ar[r ]& X^([2 ]) times X ar[l d ]ar[r d ] &\ X^([2 ])ar[r r ] & &X  $ == ref
 ref: https://doi.org/10.1112/plms.12635

