// #set page(width: 16cm, height: auto, margin: 1.5cm)
// #set page(height: auto)
// #set heading(numbering: "1.1")
// #set text(lang: "en")
// #set par(first-line-indent: 2em, justify: true)
//
#import "@preview/theorion:0.5.0": *
// #import cosmos.simple: *
#import cosmos.fancy: *
// #import cosmos.rainbow: *
// #import cosmos.clouds: *
#show: show-theorion

#import "@preview/ctheorems:1.1.3": *
#show: thmrules.with(qed-symbol: $square$)
#let thm = thmbox("thm", "Theorem", fill: rgb("#ffccff"))
#let cor = thmbox("thm", "Corollary", fill: rgb("#ffccff"))
#let def = thmbox(
  "thm",
  "Definition",
  inset: (x: 1.2em, top: 1em, bottom: 2em),
  fill: rgb("#aaaaff"),
)
#let rmk = thmbox("thm", "Remark").with(numbering: none)
#let eg = thmbox("thm", "Example", inset: (y: 2em)).with(
  inset: (x: 1.2em, top: 1em, bottom: 2em),
  fill: rgb("#fff0aa"),
  numbering: none,
)
// #let note = thmplain( "note", "Note", fill: rgb("#aaffaa"), inset: (left: 2em, top: 2em, bottom: 2em),).with(numbering: none)
// #let proof = thmproof("proof", "Proof")

= toric and foliation

#theorem[Euclid's Theorem][
  There are infinitely many prime numbers.
] <thm:euclid>


#thm[
  Let $X_(Sigma)$ be a toric variety and $cal(F)_(V)$ be a foliation corresponding to a subspace $V subset N times.o CC$
]

#def[
  A subvariety $W subset X$ is called #emph{tangent} to a foliation $cal(F)$ if the tangent space $T_W$ factors through $cal(F)$.
]
#eg[
  A subvariety $W subset X$ is called #emph{tangent} to a foliation $cal(F)$ if the tangent space $T_W$ factors through $cal(F)$.
]

#cor("algebraically integrable foliation")[
  A foliation $cal(F)_(V)$ on a toric variety $X_(sigma)$ is algebraically integrable if and only if the subspace $V subset N times.o CC$ is rational, i.e. generated by vectors in $N times.o ZZ$.
]

#rmk[
  The algebraic integrability of a foliation on a toric variety can be characterized by the rationality of the corresponding subspace in the lattice. This means that the leaves of the foliation correspond to torus-invariant subvarieties, which are determined by rational vectors in the lattice.
]

#proof[
  So
]

#note-box[
  This is interesting because it connects the geometric property of algebraic integrability of foliations with the combinatorial structure of toric varieties, allowing us to use tools from both algebraic geometry and combinatorics to study these objects.
]

What does this mean?

In note @what

```tex
\[
0 \to \mathcal{A} \to \mathcal{B} \to \mathcal{C} \to 0
\]
```


#definition[
  A natural number is called a #highlight[_prime number_] if it is greater than 1
  and cannot be written as the product of two smaller natural numbers.
] <def:prime>

#example[
  The numbers $2$, $3$, and $17$ are prime. As proven in @cor:infinite-prime,
  this list is far from complete! See @thm:euclid for the full proof.
] <what>

#assumption[
  For all $n in NN$, assume $n$ is even if $n = 2k$ for some $k in NN$.
]

#property[
  The sum of two even numbers is always even.
]

#proposition[
  There are infinitely many even numbers.
]

#remark[
  This is a remark.
]

#conjecture[Twin Prime Conjecture][
  There are infinitely many primes $p$ such that $p+2$ is also prime.
]


#proof[Proof of @thm:euclid][
  By contradiction: Suppose $p_1, p_2, dots, p_n$ is a finite enumeration of all primes.
  Let $P = p_1 p_2 dots p_n$. Since $P + 1$ is not in our list,
  it cannot be prime. Thus, some prime $p_j$ divides $P + 1$.
  Since $p_j$ also divides $P$, it must divide their difference $(P + 1) - P = 1$,
  a contradiction.
]

#corollary[
  There is no largest prime number.
] <cor:infinite-prime>

#lemma[
  There are infinitely many composite numbers.
]

== Functions and Continuity

#theorem[Continuity Theorem][
  If a function $f$ is differentiable at every point, then $f$ is continuous.
] <thm:continuous>

#tip-block[
  @thm:continuous tells us that differentiability implies continuity,
  but not vice versa. For example, $f(x) = |x|$ is continuous but not differentiable at $x = 0$.
  For a deeper understanding of continuous functions, see @thm:max-value in the appendix.
]

#note-block[
  but not vice versa. For example, $f(x) = |x|$ is continuous but not differentiable at $x = 0$.
  For a deeper understanding of continuous functions, see @thm:max-value in the appendix.
]

/// Appendix
#counter(heading).update(0)
#set heading(numbering: "A.1")
#set-theorion-numbering("A.1")

= Theorion Appendices

== Advanced Analysis

#theorem[Maximum Value Theorem][
  A continuous function on a closed interval must attain both a maximum and a minimum value.
] <thm:max-value>

#warning-block[
  Both conditions of this theorem are essential:
  - The function must be continuous
  - The domain must be a closed interval
]

== Advanced Algebra Supplements

#axiom[Group Axioms][
  A group $(G, \cdot)$ must satisfy:
  1. Closure
  2. Associativity
  3. Identity element exists
  4. Inverse elements exist
] <axiom:group>

#postulate[Fundamental Theorem of Algebra][
  Every non-zero polynomial with complex coefficients has a complex root.
] <post:fta>

#remark-block[
  This theorem is also known as Gauss's theorem, as it was first rigorously proved by Gauss.
]

== Common Problems and Solutions

#problem[
  Prove: For any integer $n > 1$, there exists a sequence of $n$ consecutive composite numbers.
]

#solution(qed: auto)[
  Consider the sequence: $n! + 2, n! + 3, ..., n! + n$

  For any $2 <= k <= n$, $n! + k$ is divisible by $k$ because:
  $n! + k = k(n! / k + 1)$

  Thus, this forms a sequence of $n-1$ consecutive composite numbers.
]

#exercise[
  1. Prove: The twin prime conjecture remains unproven.
  2. Try to explain why this problem is so difficult.
]

#conclusion[
  Number theory contains many unsolved problems that appear deceptively simple
  yet are profoundly complex.
]

== Important Notes

#note-block[
  Remember that mathematical proofs should be both rigorous and clear.
  Clarity without rigor is insufficient, and rigor without clarity is ineffective.
]

#caution-block[
  When dealing with infinite series, always verify convergence before discussing other properties.
]

#quote-block[
  Mathematics is the queen of sciences, and number theory is the queen of mathematics.
  — Gauss
]

#emph-block[
  Chapter Summary:
  - We introduced basic number theory concepts
  - Proved several important theorems
  - Demonstrated different types of mathematical environments
]

== Restated Theorems

// 1. Restate all theorems
#theorion-restate(
  filter: it => it.outlined and it.identifier == "theorem",
  render: it => it.render,
)
// 2. Restate all theorems with custom render function
// #theorion-restate(
//   filter: it => it.outlined and it.identifier == "theorem",
//   render: it => (prefix: none, title: "", full-title: auto, body) => block[#strong[#full-title.]#sym.space#emph(body)],
// )
// 3. Restate a specific theorem
// #theorion-restate(filter: it => it.label == <thm:euclid>)
// or we can use
// #theorion-restate(filter: <thm:euclid>)



== Example of appendix


#counter(heading).update(0)

#set heading(numbering: "A.1")
#set-theorion-numbering("A.1")

#problem[
  Prove: For any integer $n > 1$, there exists a sequence of $n$ consecutive composite numbers.
]

#solution(qed: auto)[
  Consider the sequence: $n! + 2, n! + 3, ..., n! + n$

  For any $2 <= k <= n$, $n! + k$ is divisible by $k$ because:
  $n! + k = k(n! / k + 1)$

  Thus, this forms a sequence of $n-1$ consecutive composite numbers.
]

#lorem(10)
